import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'background': '#fcf9f4',
        'surface': '#fcf9f4',
        'surface-bright': '#fcf9f4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3ee',
        'surface-container': '#f0ede8',
        'surface-container-high': '#ebe8e3',
        'surface-container-highest': '#e5e2dd',
        'surface-variant': '#e5e2dd',
        'surface-dim': '#dcdad5',
        'surface-tint': '#a03f29',
        'on-surface': '#1c1c19',
        'on-surface-variant': '#56423d',
        'on-background': '#1c1c19',
        'primary': '#a03f28',
        'primary-container': '#c0573e',
        'primary-fixed': '#ffdad2',
        'primary-fixed-dim': '#ffb4a3',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#3d0700',
        'on-primary-fixed-variant': '#812914',
        'on-primary-container': '#120100',
        'secondary': '#695d47',
        'secondary-container': '#f1e1c4',
        'secondary-fixed': '#f1e1c4',
        'secondary-fixed-dim': '#d4c5a9',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#6f634c',
        'on-secondary-fixed': '#221a09',
        'on-secondary-fixed-variant': '#504531',
        'tertiary': '#8b4d35',
        'tertiary-container': '#a9654b',
        'tertiary-fixed': '#ffdbce',
        'tertiary-fixed-dim': '#ffb59a',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffffff',
        'on-tertiary-fixed': '#380d00',
        'on-tertiary-fixed-variant': '#6f3720',
        'outline': '#8a726c',
        'outline-variant': '#ddc0ba',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#31302d',
        'inverse-on-surface': '#f3f0eb',
        'inverse-primary': '#ffb4a3',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Newsreader', 'serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
}

export default config
