import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'background': '#fcf9f9',
        'surface': '#fcf9f9',
        'surface-bright': '#fcf9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f3',
        'surface-container': '#f0eded',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e4e2e2',
        'surface-variant': '#e4e2e2',
        'surface-dim': '#dcd9d9',
        'surface-tint': '#745757',
        'on-surface': '#1b1b1c',
        'on-surface-variant': '#4f4444',
        'on-background': '#1b1b1c',
        'primary': '#745757',
        'primary-container': '#ad8b8b',
        'primary-fixed': '#ffdad9',
        'primary-fixed-dim': '#e3bebd',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#2b1616',
        'on-primary-fixed-variant': '#5b4040',
        'on-primary-container': '#3d2626',
        'secondary': '#655c5c',
        'secondary-container': '#e9dddd',
        'secondary-fixed': '#ece0df',
        'secondary-fixed-dim': '#cfc4c4',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#696161',
        'on-secondary-fixed': '#201a1a',
        'on-secondary-fixed-variant': '#4c4545',
        'tertiary': '#4f6357',
        'tertiary-container': '#83988b',
        'tertiary-fixed': '#d2e8d9',
        'tertiary-fixed-dim': '#b6ccbe',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#1d3026',
        'on-tertiary-fixed': '#0c1f16',
        'on-tertiary-fixed-variant': '#384b40',
        'outline': '#817474',
        'outline-variant': '#d3c3c2',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#303031',
        'inverse-on-surface': '#f3f0f0',
        'inverse-primary': '#e3bebd',
      },
      fontFamily: {
        headline: ['Noto Serif', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
}

export default config
